/* Generated By:JavaCC: Do not edit this line. TintoHeaderParser.java */
//------------------------------------------------------------------//
//                        COPYRIGHT NOTICE                          //
//------------------------------------------------------------------//
// Copyright (c) 2017, Francisco José Moreno Velo                   //
// All rights reserved.                                             //
//                                                                  //
// Redistribution and use in source and binary forms, with or       //
// without modification, are permitted provided that the following  //
// conditions are met:                                              //
//                                                                  //
// * Redistributions of source code must retain the above copyright //
//   notice, this list of conditions and the following disclaimer.  // 
//                                                                  //
// * Redistributions in binary form must reproduce the above        // 
//   copyright notice, this list of conditions and the following    // 
//   disclaimer in the documentation and/or other materials         // 
//   provided with the distribution.                                //
//                                                                  //
// * Neither the name of the University of Huelva nor the names of  //
//   its contributors may be used to endorse or promote products    //
//   derived from this software without specific prior written      // 
//   permission.                                                    //
//                                                                  //
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND           // 
// CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,      // 
// INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF         // 
// MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE         // 
// DISCLAIMED. IN NO EVENT SHALL THE COPRIGHT OWNER OR CONTRIBUTORS //
// BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,         // 
// EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED  //
// TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,    //
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND   // 
// ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT          //
// LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING   //
// IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF   //
// THE POSSIBILITY OF SUCH DAMAGE.                                  //
//------------------------------------------------------------------//

//------------------------------------------------------------------//
//                      Universidad de Huelva                       //
//          Departamento de Tecnologías de la Información           //
//   Área de Ciencias de la Computación e Inteligencia Artificial   //
//------------------------------------------------------------------//
//                                                                  //
//                  Compilador del lenguaje Tinto                   //
//                                                                  //
//------------------------------------------------------------------//


package tinto.parser;

import tinto.ast.*;
import tinto.ast.struct.*;
import java.util.Vector;

public class TintoHeaderParser implements TintoHeaderParserConstants {

        //----------------------------------------------------------------//
        //                        Miembros privados                       //
        //----------------------------------------------------------------//

        /**
	 * Contador de errores
	 */
        private int errorCount;

        /**
	 * Mensaje de errores
	 */
        private String errorMsg;

        //----------------------------------------------------------------//
        //               Método que desarrolla el análisis                //
        //----------------------------------------------------------------//

        /**
	 * Método de análisis de un fichero
	 */
        public LibraryDeclaration parse(String libname)
        {
                this.errorCount = 0;
                this.errorMsg = "";
                try
                {
                        LibraryDeclaration library = tryCompilationUnit(libname);
                        return library;
                }
                catch(Throwable e)
                {
                        catchError(e);
                        return null;
                }
        }


        //----------------------------------------------------------------//
        //       Métodos relacionados con el tratamiento de errores       //
        //----------------------------------------------------------------//

        /**
	 * Obtiene el número de errores del análisis
	 * @return
	 */
        public int getErrorCount()
        {
                return this.errorCount;
        }

        /**
	 * Obtiene el mensaje de error del análisis
	 * @return
	 */
        public String getErrorMsg()
        {
                return this.errorMsg;
        }

        /**
	 * Almacena un error de análisis
	 * @param ex
	 */
        private void catchError(Throwable ex)
        {
                this.errorCount++;
                this.errorMsg += ex.toString();
        }

        //----------------------------------------------------------------//
        //                Métodos de verificación semántica               //
        //----------------------------------------------------------------//

        /**
	 * Verifica que el nombre de la biblioteca corresponde al nombre del
	 * fichero ".tinto" 
	 */
        private boolean verifyLibraryName(Token tk, LibraryDeclaration library)
        {
                if(!tk.image.equals(library.getName()))
                {
                        int errorcode = SemanticException.LIBRARY_NAME_EXCEPTION;
                        catchError(new SemanticException(errorcode,tk));
                        return false;
                }
                return true;
        }

        /**
	 * Verifica que una cierta función no haya sido definido previamente
	 * en la biblioteca
	 */
        private boolean verifyNonDuplicatedFunction(Token tk, Function function, LibraryDeclaration library)
        {
                int[] type = function.getArgumentTypes();
                Function dup = library.getAnyFunction(tk.image,type);
                if(dup != null)
                {
                        int errorcode = SemanticException.DUPLICATE_FUNCTION_EXCEPTION;
                        catchError(new SemanticException(errorcode,tk));
                        return false;
                }
                return true;
        }

        /**
	 * Verifica que el nombre de un argumento no esté duplicado
	 */
        private boolean verifyNonDuplicatedArgument(Token tk, Vector<Variable> arguments)
        {
                if(arguments.contains(tk.image))
                {
                        int errorcode = SemanticException.DUPLICATE_ARGUMENT_EXCEPTION;
                        catchError(new SemanticException(errorcode,tk));
                        return false;
                }
                return true;
        }

        //----------------------------------------------------------------//
        //                       Acciones semánticas                      //
        //----------------------------------------------------------------//

    /**
     * Acción semántica que crea una función de una biblioteca
     */
        private void actionLibraryFunction(int acc, int type, Token tid, Vector<Variable> arguments, LibraryDeclaration library)
        {
            Function function = new Function(acc, type, tid.image, library.getName());
            function.addArgumentList(arguments);
                if(!verifyNonDuplicatedFunction(tid,function,library)) return;
                library.addFunction(function);
        }

        /**
     * Acción semántica que añade un argumento a una lista de argumentos
     */
        private void actionAddArgument(int type, Token tk, Vector<Variable> arguments)
        {
          if(!verifyNonDuplicatedArgument(tk,arguments)) return;
          arguments.add(new Variable(type, tk.image) );
        }

/**************************************************************/
/*         EL ANÁLISIS DE LA CABECERA COMIENZA AQUÍ           */
/**************************************************************/

/**
 * Reconoce el contenido completo de un archivo ".tinto"
 *
 * CompilationUnit ::= (InportClause)* TintoDecl
 */
  final public LibraryDeclaration tryCompilationUnit(String name) throws ParseException {
  int[] lsync = { };
  int[] rsync = { EOF };
  LibraryDeclaration library = null;
    try {
      library = parseCompilationUnit(name);
      jj_consume_token(0);
    } catch (Exception ex) {
    catchError(ex);
    skipTo(lsync,rsync);
    }
    {if (true) return library;}
    throw new Error("Missing return statement in function");
  }

/**
 * Reconoce el contenido completo de un archivo ".tinto"
 *
 * CompilationUnit ::= (InportClause)* TintoDecl
 */
  final public LibraryDeclaration parseCompilationUnit(String name) throws ParseException {
  Vector<String> imported = new Vector<String>();
  LibraryDeclaration library;
    label_1:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case IMPORT:
        ;
        break;
      default:
        jj_la1[0] = jj_gen;
        break label_1;
      }
      tryImportClause(imported);
    }
    library = tryTintoDecl(name, imported);
    {if (true) return library;}
    throw new Error("Missing return statement in function");
  }

/**
 * Reconoce una clausula de importación
 *
 * ImportClause ::= <IMPORT> <IDENTIFIER> <SEMICOLON> 
 */
  final public void tryImportClause(Vector<String> imported) throws ParseException {
  int[] lsync = { SEMICOLON };
  int[] rsync = { IMPORT, LIBRARY, NATIVE };
    try {
      parseImportClause(imported);
    } catch (Exception ex) {
    catchError(ex);
    skipTo(lsync,rsync);
    }
  }

/**
 * Reconoce una clausula de importación
 *
 * ImportClause ::= <IMPORT> <IDENTIFIER> <SEMICOLON> 
 */
  final public void parseImportClause(Vector<String> imported) throws ParseException {
  Token tid;
    jj_consume_token(IMPORT);
    tid = jj_consume_token(IDENTIFIER);
    jj_consume_token(SEMICOLON);
    imported.add(tid.image);
  }

/**
 * Reconoce la declaración de una biblioteca (normal o nativa)
 *
 * TintoDecl ::=  LibraryDecl |  NativeDecl 
 */
  final public LibraryDeclaration tryTintoDecl(String name, Vector<String> imported) throws ParseException {
  int[] lsync = { };
  int[] rsync = { };
  LibraryDeclaration decl = null;
    try {
      decl = parseTintoDecl(name, imported);
    } catch (Exception ex) {
    catchError(ex);
    skipTo(lsync,rsync);
    }
    {if (true) return decl;}
    throw new Error("Missing return statement in function");
  }

/**
 * Reconoce la declaración de una biblioteca (normal o nativa)
 *
 * TintoDecl ::=  LibraryDecl |  NativeDecl 
 */
  final public LibraryDeclaration parseTintoDecl(String name, Vector<String> imported) throws ParseException {
        LibraryDeclaration decl;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case LIBRARY:
      decl = tryLibraryDecl(name,imported);
      break;
    case NATIVE:
      decl = tryNativeDecl(name,imported);
      break;
    default:
      jj_la1[1] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    {if (true) return decl;}
    throw new Error("Missing return statement in function");
  }

/**
 * Reconoce la declaración de una biblioteca
 *
 * LibraryDecl ::=  <LIBRARY> <IDENTIFIER> <LBRACE> ( FunctionDecl )* <RBRACE> 
 */
  final public LibraryDeclaration tryLibraryDecl(String name, Vector<String> imported) throws ParseException {
  int[] lsync = { };
  int[] rsync = { };
  LibraryDeclaration library = new LibraryDeclaration(name);
  library.setImportedList(imported);
    try {
      parseLibraryDecl(library);
    } catch (Exception ex) {
    catchError(ex);
    skipTo(lsync,rsync);
    }
    {if (true) return library;}
    throw new Error("Missing return statement in function");
  }

/**
 * Reconoce la declaración de una biblioteca
 *
 * LibraryDecl ::=  <LIBRARY> <IDENTIFIER> <LBRACE> ( FunctionDecl )* <RBRACE> 
 */
  final public void parseLibraryDecl(LibraryDeclaration library) throws ParseException {
  Token tid;
    jj_consume_token(LIBRARY);
    tid = jj_consume_token(IDENTIFIER);
    verifyLibraryName(tid,library);
    jj_consume_token(LBRACE);
    label_2:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case PRIVATE:
      case PUBLIC:
        ;
        break;
      default:
        jj_la1[2] = jj_gen;
        break label_2;
      }
      tryFunctionDecl(library);
    }
    jj_consume_token(RBRACE);
  }

/**
 * Reconoce la declaración de una función
 *
 * FunctionDecl ::= Access FunctionType <IDENTIFIER> ArgumentDecl FunctionBody
 */
  final public void tryFunctionDecl(LibraryDeclaration library) throws ParseException {
  int[] lsync = { };
  int[] rsync = { PUBLIC, PRIVATE };
    try {
      parseFunctionDecl(library);
    } catch (Exception ex) {
    catchError(ex);
    skipTo(lsync,rsync);
    }
  }

/**
 * Reconoce la declaración de una función
 *
 * FunctionDecl ::= Access FunctionType <IDENTIFIER> ArgumentDecl FunctionBody
 */
  final public void parseFunctionDecl(LibraryDeclaration library) throws ParseException {
  int acc;
  int type;
  Token tid;
  Vector<Variable> args;
    acc = tryAccess();
    type = tryFunctionType();
    tid = jj_consume_token(IDENTIFIER);
    args = tryArgumentDecl();
    FunctionBody();
    actionLibraryFunction(acc,type,tid,args,library);
  }

/**
 * Reconoce la declaración de una biblioteca nativa
 *
 * NativeDecl ::=  <NATIVE> <IDENTIFIER> <LBRACE> ( NativeFunction )* <RBRACE> 
 */
  final public LibraryDeclaration tryNativeDecl(String name, Vector<String> imported) throws ParseException {
  int[] lsync = { };
  int[] rsync = { };
  LibraryDeclaration library = new LibraryDeclaration(name);
  library.setImportedList(imported);
  library.setNative(true);
    try {
      parseNativeDecl(library);
    } catch (Exception ex) {
    catchError(ex);
    skipTo(lsync,rsync);
    }
    {if (true) return library;}
    throw new Error("Missing return statement in function");
  }

/**
 * Reconoce la declaración de una biblioteca nativa
 *
 * NativeDecl ::=  <NATIVE> <IDENTIFIER> <LBRACE> ( NativeFunction )* <RBRACE> 
 */
  final public void parseNativeDecl(LibraryDeclaration library) throws ParseException {
  Token tid;
    jj_consume_token(NATIVE);
    tid = jj_consume_token(IDENTIFIER);
    verifyLibraryName(tid,library);
    jj_consume_token(LBRACE);
    label_3:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case PRIVATE:
      case PUBLIC:
        ;
        break;
      default:
        jj_la1[3] = jj_gen;
        break label_3;
      }
      tryNativeFunction(library);
    }
    jj_consume_token(RBRACE);
  }

/**
 * Reconoce la declaración de una función de una biblioteca nativa
 *
 * NativeFunction ::= Access FunctionType <IDENTIFIER> ArgumentDecl <SEMICOLON>
 */
  final public void tryNativeFunction(LibraryDeclaration library) throws ParseException {
  int[] lsync = { };
  int[] rsync = { PUBLIC, PRIVATE };
    try {
      parseNativeFunction(library);
    } catch (Exception ex) {
    catchError(ex);
    skipTo(lsync,rsync);
    }
  }

/**
 * Reconoce la declaración de una función de una biblioteca nativa
 *
 * NativeFunction ::= Access FunctionType <IDENTIFIER> ArgumentDecl <SEMICOLON>
 */
  final public void parseNativeFunction(LibraryDeclaration library) throws ParseException {
  int acc;
  int type;
  Token tid;
  Vector<Variable> args;
    acc = tryAccess();
    type = tryFunctionType();
    tid = jj_consume_token(IDENTIFIER);
    args = tryArgumentDecl();
    jj_consume_token(SEMICOLON);
    actionLibraryFunction(acc,type,tid,args,library);
  }

/**
 * Reconoce un modificador de acceso
 *
 * Access ::= <PUBLIC> | <PRIVATE>
 */
  final public int tryAccess() throws ParseException {
  int[] lsync = { };
  int[] rsync = { VOID, INT, CHAR, BOOLEAN };
  int acc = Access.PUBLIC_ACCESS;
    try {
      acc = parseAccess();
    } catch (Exception ex) {
    catchError(ex);
    skipTo(lsync,rsync);
    }
    {if (true) return acc;}
    throw new Error("Missing return statement in function");
  }

/**
 * Reconoce un modificador de acceso
 *
 * Access ::= <PUBLIC> | <PRIVATE>
 */
  final public int parseAccess() throws ParseException {
  int acc;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case PUBLIC:
      jj_consume_token(PUBLIC);
               acc = Access.PUBLIC_ACCESS;
      break;
    case PRIVATE:
      jj_consume_token(PRIVATE);
                acc = Access.PRIVATE_ACCESS;
      break;
    default:
      jj_la1[4] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    {if (true) return acc;}
    throw new Error("Missing return statement in function");
  }

/**
 * Reconoce el tipo de datos que devuelve una función
 *
 * FunctionType ::= Type | <VOID>
 */
  final public int tryFunctionType() throws ParseException {
  int[] lsync = { };
  int[] rsync = { IDENTIFIER };
  int type = Type.MISMATCH_TYPE;
    try {
      type = parseFunctionType();
    } catch (Exception ex) {
    catchError(ex);
    skipTo(lsync,rsync);
    }
    {if (true) return type;}
    throw new Error("Missing return statement in function");
  }

/**
 * Reconoce el tipo de datos que devuelve una función
 *
 * FunctionType ::= Type | <VOID>
 */
  final public int parseFunctionType() throws ParseException {
  int type = Type.MISMATCH_TYPE;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case BOOLEAN:
    case CHAR:
    case INT:
      type = tryType();
      break;
    case VOID:
      jj_consume_token(VOID);
              type = Type.VOID_TYPE;
      break;
    default:
      jj_la1[5] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    {if (true) return type;}
    throw new Error("Missing return statement in function");
  }

/**
 * Reconoce un tipo de datos básico
 *
 * Type ::= <INT> | <CHAR> | <BOOLEAN>
 */
  final public int tryType() throws ParseException {
  int[] lsync = { };
  int[] rsync = { IDENTIFIER };
  int type = Type.MISMATCH_TYPE;
    try {
      type = parseType();
    } catch (Exception ex) {
    catchError(ex);
    skipTo(lsync,rsync);
    }
    {if (true) return type;}
    throw new Error("Missing return statement in function");
  }

/**
 * Reconoce un tipo de datos básico
 *
 * Type ::= <INT> | <CHAR> | <BOOLEAN>
 */
  final public int parseType() throws ParseException {
  int type;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case INT:
      jj_consume_token(INT);
            type = Type.INT_TYPE;
      break;
    case CHAR:
      jj_consume_token(CHAR);
             type = Type.CHAR_TYPE;
      break;
    case BOOLEAN:
      jj_consume_token(BOOLEAN);
                type = Type.BOOLEAN_TYPE;
      break;
    default:
      jj_la1[6] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    {if (true) return type;}
    throw new Error("Missing return statement in function");
  }

/**
 * Reconoce la declaración de argumentos de una función
 *
 * ArgumentDecl ::= <LPAREN> ( Argument ( <COMMA> Argument )* )? <RPAREN>
 */
  final public Vector<Variable> tryArgumentDecl() throws ParseException {
  int[] lsync = { RPAREN };
  int[] rsync = { LBRACE };
  Vector<Variable> args = null;
    try {
      args = parseArgumentDecl();
    } catch (Exception ex) {
    catchError(ex);
    skipTo(lsync,rsync);
    }
    {if (true) return args;}
    throw new Error("Missing return statement in function");
  }

/**
 * Reconoce la declaración de argumentos de una función
 *
 * ArgumentDecl ::= <LPAREN> ( Argument ( <COMMA> Argument )* )? <RPAREN>
 */
  final public Vector<Variable> parseArgumentDecl() throws ParseException {
  Vector<Variable> args = new Vector<Variable>();
    jj_consume_token(LPAREN);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case BOOLEAN:
    case CHAR:
    case INT:
      tryArgument(args);
      label_4:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case COMMA:
          ;
          break;
        default:
          jj_la1[7] = jj_gen;
          break label_4;
        }
        jj_consume_token(COMMA);
        tryArgument(args);
      }
      break;
    default:
      jj_la1[8] = jj_gen;
      ;
    }
    jj_consume_token(RPAREN);
    {if (true) return args;}
    throw new Error("Missing return statement in function");
  }

/**
 * Reconoce la declaración de un argumento
 *
 * Argument ::= Type <IDENTIFIER>
 */
  final public void tryArgument(Vector<Variable> args) throws ParseException {
  int[] lsync = { };
  int[] rsync = { COMMA, RPAREN };
    try {
      parseArgument(args);
    } catch (Exception ex) {
    catchError(ex);
    skipTo(lsync,rsync);
    }
  }

/**
 * Reconoce la declaración de un argumento
 *
 * Argument ::= Type <IDENTIFIER>
 */
  final public void parseArgument(Vector<Variable> args) throws ParseException {
  int type;
  Token tid;
    type = tryType();
    tid = jj_consume_token(IDENTIFIER);
    actionAddArgument(type,tid,args);
  }

  void FunctionBody() throws ParseException {
  Token tk = getNextToken();  // Consume el caracter "{"
  int level = 1;
  while(level != 0)
  {
    tk = getNextToken();
        if(tk.kind == EOF) break;
    else if(tk.kind == LBRACE) level ++;
    else if(tk.kind == RBRACE) level --;
  }
  }

  void skipTo(int[] left, int[] right) throws ParseException {
  Token prev = getToken(0);
  Token next = getToken(1);
  boolean flag = false;
  if(prev.kind == EOF || next.kind == EOF) flag = true;
  for(int i=0; i<left.length; i++) if(prev.kind == left[i]) flag = true;
  for(int i=0; i<right.length; i++) if(next.kind == right[i]) flag = true;

  while(!flag)
  {
    getNextToken();
    prev = getToken(0);
    next = getToken(1);
    if(prev.kind == EOF || next.kind == EOF) flag = true;
    for(int i=0; i<left.length; i++) if(prev.kind == left[i]) flag = true;
    for(int i=0; i<right.length; i++) if(next.kind == right[i]) flag = true;
  }
  }

  /** Generated Token Manager. */
  public TintoHeaderParserTokenManager token_source;
  SimpleCharStream jj_input_stream;
  /** Current token. */
  public Token token;
  /** Next token. */
  public Token jj_nt;
  private int jj_ntk;
  private int jj_gen;
  final private int[] jj_la1 = new int[9];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static {
      jj_la1_init_0();
      jj_la1_init_1();
   }
   private static void jj_la1_init_0() {
      jj_la1_0 = new int[] {0x2000,0x18000,0x60000,0x60000,0x60000,0x204300,0x4300,0x0,0x4300,};
   }
   private static void jj_la1_init_1() {
      jj_la1_1 = new int[] {0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x8,0x0,};
   }

  /** Constructor with InputStream. */
  public TintoHeaderParser(java.io.InputStream stream) {
     this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public TintoHeaderParser(java.io.InputStream stream, String encoding) {
    try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new TintoHeaderParserTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 9; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 9; i++) jj_la1[i] = -1;
  }

  /** Constructor. */
  public TintoHeaderParser(java.io.Reader stream) {
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new TintoHeaderParserTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 9; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 9; i++) jj_la1[i] = -1;
  }

  /** Constructor with generated Token Manager. */
  public TintoHeaderParser(TintoHeaderParserTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 9; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(TintoHeaderParserTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 9; i++) jj_la1[i] = -1;
  }

  private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }


/** Get the next Token. */
  final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

/** Get the specific Token. */
  final public Token getToken(int index) {
    Token t = token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  private int jj_ntk() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  private int[] jj_expentry;
  private int jj_kind = -1;

  /** Generate ParseException. */
  public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[59];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 9; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
          if ((jj_la1_1[i] & (1<<j)) != 0) {
            la1tokens[32+j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 59; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  /** Enable tracing. */
  final public void enable_tracing() {
  }

  /** Disable tracing. */
  final public void disable_tracing() {
  }

}
