/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.awt.Color;

/**
 *
 * @author theen
 */
public class PilaFrame extends java.awt.Frame {

    private static final int ANCHO = 500, ALTO = 1000, CAPACIDAD = 10;
    
    /**
     * Creates new form PilaFrame
     */
    public PilaFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws InterruptedException {
        PilaFrame f = new PilaFrame();
        CanvasPila canvas = new CanvasPila(CAPACIDAD);
        canvas.setSize(ANCHO, ALTO);
        canvas.setBackground(Color.white);
        f.setSize(ANCHO,ALTO);
        f.add(canvas);
        f.setTitle("Practica 4 realizada por Juan Manuel Ruiz Pérez");
        f.setResizable(false);
        f.setLocationRelativeTo(null);
        f.setVisible(true);
        
        Pilalenta p = new Pilalenta(CAPACIDAD,canvas);
        
        Productor[] h1 = new Productor[4];
        Thread Consumidor = new Thread(new Consumidor(p));
        
        for (int i = 0; i < 4; i++) {
            h1[i] = new Productor(p);
            h1[i].start();
        }

        Consumidor.start();
        
        Consumidor.join();
        
        for (int i = 0; i < 4; i++) {
            h1[i].join();
        }
               
        Thread.sleep(3000);
        System.exit(0);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
