/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/AWTForms/Frame.java to edit this template
 */
package pila;

import java.awt.Color;
import static java.lang.Thread.sleep;

/**
 *
 * @author Alberto Fernández
 */
public class PilaFrame extends java.awt.Frame {

    /**
     * Creates new form PilaFrame
     */
    private static final int ANCHO = 500;
    private static final int ALTO = 800;
    private static final int CAPACIDAD = 10;

    private static final int PRODUCTORES = 4;
    private static final int CONSUMIDORES = 1;

    public PilaFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setPreferredSize(new java.awt.Dimension(600, 600));
        setTitle("Pila Gráfica");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws InterruptedException {

        //Creo la ventana principal.
        PilaFrame pilaGrafica = new PilaFrame();
        pilaGrafica.setSize(ANCHO, ALTO);
        pilaGrafica.setBackground(Color.decode("#0B2611"));  //#B0F3BE
        //Creo el canvas donde pintar la pila
        CanvasPila lienzo = new CanvasPila(CAPACIDAD);
        lienzo.setSize(ANCHO, ALTO);
        lienzo.setBackground(Color.decode("#5CBD70"));
        //Añado el lienzo a la ventana principal
        pilaGrafica.add(lienzo);
        //Pongo visible la ventana principal.
        pilaGrafica.setVisible(true);

        //Creo la pila.
        PilaLenta pila = new PilaLenta(CAPACIDAD, lienzo);
        //Creo el ordenador que permitirá saber si un productor puede apilar
        Ordenador o = new Ordenador(pila, CAPACIDAD);

        //Creo el array de productores y de consumidores
        productor productores[] = new productor[PRODUCTORES]; //extends Thread
        Thread consumidoresH[] = new Thread[CONSUMIDORES];

        //Inicializo los productores
        for (int i = 0; i < PRODUCTORES; i++) {
            productores[i] = new productor(pila, o);
        }
        //Inicializo los consumidores
        for (int i = 0; i < CONSUMIDORES; i++) {
            consumidoresH[i] = new Thread(new consumidor(pila, o));
        }
        //Empiezan a funcionar los productores
        for (int i = 0; i < PRODUCTORES; i++) {
            productores[i].start();
        }
        //Empiezan a funcionar los consumidores
        for (int i = 0; i < CONSUMIDORES; i++) {
            consumidoresH[i].start();
        }

        //Espero a que acaben los consumidores
        for (int i = 0; i < CONSUMIDORES; i++) {
            consumidoresH[i].join();
        }
        
        System.out.println("Los consumidores han acabado");
            //Una vez acaben los consumidores, le mando un notify a todos los productores
            //mientras estén activos.

        for (int i = 0; i < PRODUCTORES; i++) {
            while (productores[i].isAlive()) {
                synchronized (o) {
                    o.notifyAll();
                }
            }
            sleep(1000);
        }
        
        for (int i = 0; i < CONSUMIDORES; i++) {
            while (consumidoresH[i].isAlive()) {
                synchronized (o) {
                    o.notifyAll();
                }
            }
            sleep(1000);
        }
        for (int i = 0; i < PRODUCTORES; i++) {
            productores[i].join();
        }

        System.out.println("Los productores han acabado");
        
        sleep(3000);
        System.exit(0);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
