/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ejemploframe;

import java.awt.Color;

/**
 *
 * @author usuario
 */
public class EjemploAPP extends java.awt.Frame {

    /**
     * Creates new form EjemploAPP
     */
    public EjemploAPP() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonSalir = new java.awt.Button();

        setPreferredSize(new java.awt.Dimension(200, 240));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        botonSalir.setActionCommand("botonsalir");
        botonSalir.setBackground(new java.awt.Color(204, 255, 51));
        botonSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        botonSalir.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        botonSalir.setForeground(new java.awt.Color(255, 0, 0));
        botonSalir.setLabel("Salir");
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });
        add(botonSalir, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_botonSalirActionPerformed

    /**
     * @param args the command line arguments
     * @throws java.lang.InterruptedException
     */
    public static void main(String args[]) throws InterruptedException {
        
        EjemploAPP f = new EjemploAPP();
        
        f.setSize(600,400);
        Lienzo cv = new Lienzo(f.getWidth(),(f.getHeight()));
        f.add(cv);
        f.setBackground(Color.cyan);
        f.setTitle("Ejemplo de Frame");
        f.setVisible(true);
        
        
        
        
      Recurso r = new Recurso(cv);
        Hilo h[] = new Hilo[5];

        for (int i = 0; i < h.length; i++) {
            if (i % 2 == 0) {
                h[i] = new Hilo(r, 0);
            } else {
                h[i] = new Hilo(r, 1);
            }

        }

        for (int i = 0; i < h.length; i++) {

            h[i].start();

        }

        for (int i = 0; i < h.length; i++) {
            h[i].join();
        }
        r.verContadores();

    
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public java.awt.Button botonSalir;
    // End of variables declaration//GEN-END:variables
}
